using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StudentInformationColumnParser.DTOs
{
    class CampusStudent1011
    {
        public int BA0GH10N { get; set; }
        public int BA0GM10N { get; set; }
        public int BA0GR10N { get; set; }
        public int BB0GR10N { get; set; }
        public int BH0GR10N { get; set; }
        public int BI0GR10N { get; set; }
        public int BPEMALLP { get; set; }
        public int BPERRA1R { get; set; }
        public int BPERRA2R { get; set; }
        public int BPERRA3R { get; set; }
        public int BPERRA4R { get; set; }
        public int BPERRA5R { get; set; }
        public int BPERRA6R { get; set; }
        public int BPERRA7R { get; set; }
        public int BPERRA8R { get; set; }
        public int BPERRAKR { get; set; }
        public int BPERSA1R { get; set; }
        public int BPERSA2R { get; set; }
        public int BPERSA3R { get; set; }
        public int BPERSA4R { get; set; }
        public int BPERSA5R { get; set; }
        public int BPERSA6R { get; set; }
        public int BPERSA7R { get; set; }
        public int BPERSA8R { get; set; }
        public int BPERSAKR { get; set; }
        public int BPETALLC { get; set; }
        public int BPETASIP { get; set; }
        public int BPETBILP { get; set; }
        public int BPETBLAP { get; set; }
        public int BPETDISP { get; set; }
        public int BPETECOP { get; set; }
        public int BPETG01P { get; set; }
        public int BPETG02P { get; set; }
        public int BPETG03P { get; set; }
        public int BPETG04P { get; set; }
        public int BPETG05P { get; set; }
        public int BPETG06P { get; set; }
        public int BPETG07P { get; set; }
        public int BPETG08P { get; set; }
        public int BPETG09P { get; set; }
        public int BPETG10P { get; set; }
        public int BPETG11P { get; set; }
        public int BPETG12P { get; set; }
        public int BPETGEEP { get; set; }
        public int BPETGIFP { get; set; }
        public int BPETGKNP { get; set; }
        public int BPETGPKP { get; set; }
        public int BPETHISP { get; set; }
        public int BPETINDP { get; set; }
        public int BPETLEPP { get; set; }
        public int BPETPCIP { get; set; }
        public int BPETRSKP { get; set; }
        public int BPETSPEP { get; set; }
        public int BPETTWOP { get; set; }
        public int BPETVOCP { get; set; }
        public int BPETWHIP { get; set; }
        public int BS0GR10N { get; set; }
        public int BW0GR10N { get; set; }
        public int CA0GH10N { get; set; }
        public int CA0GH10P { get; set; }
        public int CA0GM10N { get; set; }
        public int CA0GM10P { get; set; }
        public int CA0GR10N { get; set; }
        public int CB0GR10N { get; set; }
        public int CB0GR10P { get; set; }
        public int CH0GR10N { get; set; }
        public int CH0GR10P { get; set; }
        public int CI0GR10N { get; set; }
        public int CI0GR10P { get; set; }
        public int CPEMALLC { get; set; }
        public int CPEMALLP { get; set; }
        public int CPERRA1R { get; set; }
        public int CPERRA2R { get; set; }
        public int CPERRA3R { get; set; }
        public int CPERRA4R { get; set; }
        public int CPERRA5R { get; set; }
        public int CPERRA6R { get; set; }
        public int CPERRA7R { get; set; }
        public int CPERRA8R { get; set; }
        public int CPERRAKR { get; set; }
        public int CPERSA1R { get; set; }
        public int CPERSA2R { get; set; }
        public int CPERSA3R { get; set; }
        public int CPERSA4R { get; set; }
        public int CPERSA5R { get; set; }
        public int CPERSA6R { get; set; }
        public int CPERSA7R { get; set; }
        public int CPERSA8R { get; set; }
        public int CPERSAKR { get; set; }
        public int CPETALLC { get; set; }
        public int CPETASIC { get; set; }
        public int CPETASIP { get; set; }
        public int CPETBILC { get; set; }
        public int CPETBILP { get; set; }
        public int CPETBLAC { get; set; }
        public int CPETBLAP { get; set; }
        public int CPETDISC { get; set; }
        public int CPETDISP { get; set; }
        public int CPETECOC { get; set; }
        public int CPETECOP { get; set; }
        public int CPETG01C { get; set; }
        public int CPETG01P { get; set; }
        public int CPETG02C { get; set; }
        public int CPETG02P { get; set; }
        public int CPETG03C { get; set; }
        public int CPETG03P { get; set; }
        public int CPETG04C { get; set; }
        public int CPETG04P { get; set; }
        public int CPETG05C { get; set; }
        public int CPETG05P { get; set; }
        public int CPETG06C { get; set; }
        public int CPETG06P { get; set; }
        public int CPETG07C { get; set; }
        public int CPETG07P { get; set; }
        public int CPETG08C { get; set; }
        public int CPETG08P { get; set; }
        public int CPETG09C { get; set; }
        public int CPETG09P { get; set; }
        public int CPETG10C { get; set; }
        public int CPETG10P { get; set; }
        public int CPETG11C { get; set; }
        public int CPETG11P { get; set; }
        public int CPETG12C { get; set; }
        public int CPETG12P { get; set; }
        public int CPETGEEC { get; set; }
        public int CPETGEEP { get; set; }
        public int CPETGIFC { get; set; }
        public int CPETGIFP { get; set; }
        public int CPETGKNC { get; set; }
        public int CPETGKNP { get; set; }
        public int CPETGPKC { get; set; }
        public int CPETGPKP { get; set; }
        public int CPETHISC { get; set; }
        public int CPETHISP { get; set; }
        public int CPETINDC { get; set; }
        public int CPETINDP { get; set; }
        public int CPETLEPC { get; set; }
        public int CPETLEPP { get; set; }
        public int CPETPCIC { get; set; }
        public int CPETPCIP { get; set; }
        public int CPETRSKC { get; set; }
        public int CPETRSKP { get; set; }
        public int CPETSPEC { get; set; }
        public int CPETSPEP { get; set; }
        public int CPETTWOC { get; set; }
        public int CPETTWOP { get; set; }
        public int CPETVOCC { get; set; }
        public int CPETVOCP { get; set; }
        public int CPETWHIC { get; set; }
        public int CPETWHIP { get; set; }
        public int CS0GR10N { get; set; }
        public int CS0GR10P { get; set; }
        public int CW0GR10N { get; set; }
        public int CW0GR10P { get; set; }
        public int B20GR10N { get; set; }
        public int B30GR10N { get; set; }
        public int B40GR10N { get; set; }
        public int C20GR10N { get; set; }
        public int C20GR10P { get; set; }
        public int C30GR10N { get; set; }
        public int C30GR10P { get; set; }
        public int C40GR10N { get; set; }
        public int C40GR10P { get; set; }

    }
}
