// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Infrastructure.EntityMapping.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201410032207037_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
